### ISSUE TITLE
Integration w/ Bootstrap

### ISSUE THREAD

**Issue by loganfranken** [UCSantaBarbara/ucsb-web-ui-kit#1]
Hey @garster!

I need to do a UC branding refresh for a couple of my websites and I wanted to use Bootstrap since it's become a standard in our department. I was just wondering about your vision for how this UI kit possibly integrates w/ a Boostrap theme? (Or how it doesn't?)

**Comment by ilessing** [comment]
This project's ReadMe -> [Roadmap](https://github.com/UCSantaBarbara/ucsb-web-ui-kit#roadmap-plans-goals-hopes-and-dreams) excludes Bootstrap but I'm interested in the idea of a [Bootstrap theme](https://getbootstrap.com/docs/4.1/getting-started/theming/) that implements the [UCSB visual identity guidelines](https://www.ucsb.edu/visual-identity).  Maybe that is a separate project than this one??

**Comment by garster** [comment]
@loganfranken I love Bootstrap, it gives you so much for so little effort. We in ARIT have been using it all over the place but we are moving to React and have settled on Material-UI component library. So for my selfish reason I want to use this UCSB style in all that! The source material for this is written in SCSS and uses the Bootstrap theme in Drupal.

I want to make this compatible with Bootstrap, but not require it. For example you would just add one more class to a Bootstrap button to get the UCSB button. ```<button class="btn ucsb-btn">Go</button>```

I think Bootstrap does a great job of documenting and design and I would like to imitate that. It may not work out in the end but we will see. I expect to ramp up on this project as I have just cleared out some other obligations. I want to do buttons next, but also spin up a bunch of issues with the Drupal code and an screenshot of the final product, then get others like you involved!

Thanks @ilessing for chiming in!

**Comment by garster** [comment]
To me a Bootstrap theme will override the Bootstrap classes. I want code to be 100% optional, so you can include the css file but it will change nothing unless you use of of the classes. So I want this to work hand in hand with Bootstrap, but also be usable everywhere.

**Comment by loganfranken** [comment]
Okay, gotcha! Thank you both for the input!

It sounds like a Bootstrap theme will work best for our needs so we'll probably head down that road, but I'll keep thinking about how our work in that area could integrate with this project as well. Thanks!
